modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
issueTrackerURL="https://github.com/SnappyDragon18/Musical-Foxes/issues"

[[mods]]
  modId="musicalfoxes"
  version="1.0.2"
  displayName="Musical Foxes"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/musical-foxes"
  authors="SchnappDragon"
  description='''Lets foxes play goat horns.'''

  [[dependencies.musicalfoxes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4, 1.20)"
    ordering="NONE"
    side="BOTH"